# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
 - &filter-only-source
   branches:
     only:
       - source

version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "eransharv@users.noreply.github.com"
            git config --global user.name "eransharv"
            echo "machine github.com login eransharv password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=eransharv CURRENT_BRANCH=source yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
         filters: *filter-only-source